// Code generated by MockGen. DO NOT EDIT.
// Source: application/carApplication.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entity "github.com/TulioGuaraldoB/car-app/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockICarApplication is a mock of ICarApplication interface.
type MockICarApplication struct {
	ctrl     *gomock.Controller
	recorder *MockICarApplicationMockRecorder
}

// MockICarApplicationMockRecorder is the mock recorder for MockICarApplication.
type MockICarApplicationMockRecorder struct {
	mock *MockICarApplication
}

// NewMockICarApplication creates a new mock instance.
func NewMockICarApplication(ctrl *gomock.Controller) *MockICarApplication {
	mock := &MockICarApplication{ctrl: ctrl}
	mock.recorder = &MockICarApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICarApplication) EXPECT() *MockICarApplicationMockRecorder {
	return m.recorder
}

// CreateCar mocks base method.
func (m *MockICarApplication) CreateCar(car *entity.Car) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCar", car)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCar indicates an expected call of CreateCar.
func (mr *MockICarApplicationMockRecorder) CreateCar(car interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCar", reflect.TypeOf((*MockICarApplication)(nil).CreateCar), car)
}

// DeleteCar mocks base method.
func (m *MockICarApplication) DeleteCar(carId uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCar", carId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCar indicates an expected call of DeleteCar.
func (mr *MockICarApplicationMockRecorder) DeleteCar(carId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCar", reflect.TypeOf((*MockICarApplication)(nil).DeleteCar), carId)
}

// GetAllCars mocks base method.
func (m *MockICarApplication) GetAllCars() ([]entity.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCars")
	ret0, _ := ret[0].([]entity.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCars indicates an expected call of GetAllCars.
func (mr *MockICarApplicationMockRecorder) GetAllCars() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCars", reflect.TypeOf((*MockICarApplication)(nil).GetAllCars))
}

// GetCarById mocks base method.
func (m *MockICarApplication) GetCarById(carId uint) (*entity.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCarById", carId)
	ret0, _ := ret[0].(*entity.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCarById indicates an expected call of GetCarById.
func (mr *MockICarApplicationMockRecorder) GetCarById(carId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCarById", reflect.TypeOf((*MockICarApplication)(nil).GetCarById), carId)
}

// GetCarByLicensePlate mocks base method.
func (m *MockICarApplication) GetCarByLicensePlate(licensePlate string) (*entity.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCarByLicensePlate", licensePlate)
	ret0, _ := ret[0].(*entity.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCarByLicensePlate indicates an expected call of GetCarByLicensePlate.
func (mr *MockICarApplicationMockRecorder) GetCarByLicensePlate(licensePlate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCarByLicensePlate", reflect.TypeOf((*MockICarApplication)(nil).GetCarByLicensePlate), licensePlate)
}

// GetCarsByBrand mocks base method.
func (m *MockICarApplication) GetCarsByBrand(brand string) ([]entity.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCarsByBrand", brand)
	ret0, _ := ret[0].([]entity.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCarsByBrand indicates an expected call of GetCarsByBrand.
func (mr *MockICarApplicationMockRecorder) GetCarsByBrand(brand interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCarsByBrand", reflect.TypeOf((*MockICarApplication)(nil).GetCarsByBrand), brand)
}
