// Code generated by MockGen. DO NOT EDIT.
// Source: infrastructure/service/crossService.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dto "github.com/TulioGuaraldoB/car-app/infrastructure/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockICrossService is a mock of ICrossService interface.
type MockICrossService struct {
	ctrl     *gomock.Controller
	recorder *MockICrossServiceMockRecorder
}

// MockICrossServiceMockRecorder is the mock recorder for MockICrossService.
type MockICrossServiceMockRecorder struct {
	mock *MockICrossService
}

// NewMockICrossService creates a new mock instance.
func NewMockICrossService(ctrl *gomock.Controller) *MockICrossService {
	mock := &MockICrossService{ctrl: ctrl}
	mock.recorder = &MockICrossServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICrossService) EXPECT() *MockICrossServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockICrossService) Login(credentialsRequest *dto.Credentials) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", credentialsRequest)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockICrossServiceMockRecorder) Login(credentialsRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockICrossService)(nil).Login), credentialsRequest)
}

// Register mocks base method.
func (m *MockICrossService) Register(userRequest *dto.UserRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", userRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockICrossServiceMockRecorder) Register(userRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockICrossService)(nil).Register), userRequest)
}
